#!/bin/bash
echo "Please note: the secret will be shown here and will NOT be saved. You MUST have your hardware key or equivalent to regenerate the secret. Saving your secret locally defeat the whole purpose of this tool."
echo "--"

fido2-hmac-secret generate -f "$1"
